### ISSUE TITLE
Hello, I found you because I was looking for the same thing.

### ISSUE THREAD

**Issue by sebastianarca** [Aisbergg/python-docker-compose-templer#3]
Estuve buscando hacer algo muy similar. ¿Queria saber si habias encontrado una mejor solucion ?

I was looking to do something very similar. I wanted to know if you had found a better solution?

**Comment by aisbergg** [comment]
Hi, I don't work as much with docker-compose files anymore, but I can give you some hints. Starting with Docker Compose release v2, they rewrote the software and unified the different Compose File References, which is now the [Compose Spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md). There is the option [`extends`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#extends) that allows to base a service configuration on another one from a different Compose File. Furthermore you can also use YAML anchors to use [fragments](https://github.com/compose-spec/compose-spec/blob/master/spec.md#fragments) for common options
